"""ddd

Revision ID: 0d0e934701f0
Revises: e513c2772ad2
Create Date: 2022-10-07 23:30:13.174916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d0e934701f0'
down_revision = 'e513c2772ad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('editor', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'editor')
    # ### end Alembic commands ###
