"""user img

Revision ID: cc032ec35ee2
Revises: 1f61b0c9e3aa
Create Date: 2022-02-27 15:28:50.852164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc032ec35ee2'
down_revision = '1f61b0c9e3aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('img_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'img_url')
    # ### end Alembic commands ###
